const express = require('express');
const ctrl = require('./usuarios.controller');
const { authMiddleware } = require('../../middleware/authMiddleware');
const { requireAdmin } = require('../../middleware/roleMiddleware');
const router = express.Router();
router.get('/', authMiddleware, ctrl.getAll);
router.get('/roles', authMiddleware, ctrl.getRoles);
router.post('/roles', authMiddleware, requireAdmin, ctrl.createRole);
router.post('/', authMiddleware, requireAdmin, ctrl.create);
router.put('/:id', authMiddleware, requireAdmin, ctrl.update);
router.post('/:id/reset-password', authMiddleware, requireAdmin, ctrl.resetPassword);
router.post('/:id/toggle-active', authMiddleware, requireAdmin, ctrl.toggleActive);
module.exports = router;
