const express = require('express');
const ctrl = require('./facturacion.controller');
const { authMiddleware } = require('../../middleware/authMiddleware');
const { requireAdmin } = require('../../middleware/roleMiddleware');
const router = express.Router();
router.get('/', authMiddleware, ctrl.getAll);
router.get('/ncf', authMiddleware, ctrl.getNcfSequences);
router.post('/ncf', authMiddleware, requireAdmin, ctrl.createNcfSequence);
router.put('/ncf/:id', authMiddleware, requireAdmin, ctrl.updateNcfSequence);
router.get('/dgii-dashboard', authMiddleware, ctrl.getDgiiDashboardData);
router.get('/formatos-dgii', authMiddleware, ctrl.getFormatosDgii);
router.get('/export-606', authMiddleware, ctrl.export606);
router.get('/export-607', authMiddleware, ctrl.export607);
router.get('/export-608', authMiddleware, ctrl.export608);
router.get('/configuracion', authMiddleware, ctrl.getConfiguracionFiscal);
router.put('/configuracion', authMiddleware, requireAdmin, ctrl.updateConfiguracionFiscal);
router.get('/auditoria-fiscal', authMiddleware, ctrl.getAuditoriaFiscal);
router.get('/:id', authMiddleware, ctrl.getById);
router.post('/', authMiddleware, ctrl.createInvoice);
router.post('/:id/cancel', authMiddleware, requireAdmin, ctrl.cancelInvoice);
module.exports = router;
