const express = require('express');
const ctrl = require('./reportes.controller');
const { authMiddleware } = require('../../middleware/authMiddleware');
const { requireAdmin } = require('../../middleware/roleMiddleware');
const router = express.Router();
router.get('/ventas', authMiddleware, requireAdmin, ctrl.getSalesReport);
router.get('/inventario', authMiddleware, requireAdmin, ctrl.getInventoryReport);
router.get('/top-productos', authMiddleware, requireAdmin, ctrl.getTopProducts);
router.get('/caja', authMiddleware, requireAdmin, ctrl.getCashReport);
module.exports = router;
